//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetLogDLL.GetLog {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordLog", Namespace="http://schemas.datacontract.org/2004/07/GetLogWCF")]
    [System.SerializableAttribute()]
    public partial class RecordLog : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlApiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> rlDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlDeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlDeviceTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlElementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long rlIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlIsShowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlMachineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlMsgTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlSolutionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rlStepField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlApi {
            get {
                return this.rlApiField;
            }
            set {
                if ((object.ReferenceEquals(this.rlApiField, value) != true)) {
                    this.rlApiField = value;
                    this.RaisePropertyChanged("rlApi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> rlDate {
            get {
                return this.rlDateField;
            }
            set {
                if ((this.rlDateField.Equals(value) != true)) {
                    this.rlDateField = value;
                    this.RaisePropertyChanged("rlDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlDeviceId {
            get {
                return this.rlDeviceIdField;
            }
            set {
                if ((object.ReferenceEquals(this.rlDeviceIdField, value) != true)) {
                    this.rlDeviceIdField = value;
                    this.RaisePropertyChanged("rlDeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlDeviceType {
            get {
                return this.rlDeviceTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.rlDeviceTypeField, value) != true)) {
                    this.rlDeviceTypeField = value;
                    this.RaisePropertyChanged("rlDeviceType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlElement {
            get {
                return this.rlElementField;
            }
            set {
                if ((object.ReferenceEquals(this.rlElementField, value) != true)) {
                    this.rlElementField = value;
                    this.RaisePropertyChanged("rlElement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long rlId {
            get {
                return this.rlIdField;
            }
            set {
                if ((this.rlIdField.Equals(value) != true)) {
                    this.rlIdField = value;
                    this.RaisePropertyChanged("rlId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlIsShow {
            get {
                return this.rlIsShowField;
            }
            set {
                if ((object.ReferenceEquals(this.rlIsShowField, value) != true)) {
                    this.rlIsShowField = value;
                    this.RaisePropertyChanged("rlIsShow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlMachine {
            get {
                return this.rlMachineField;
            }
            set {
                if ((object.ReferenceEquals(this.rlMachineField, value) != true)) {
                    this.rlMachineField = value;
                    this.RaisePropertyChanged("rlMachine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlMsg {
            get {
                return this.rlMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.rlMsgField, value) != true)) {
                    this.rlMsgField = value;
                    this.RaisePropertyChanged("rlMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlMsgTag {
            get {
                return this.rlMsgTagField;
            }
            set {
                if ((object.ReferenceEquals(this.rlMsgTagField, value) != true)) {
                    this.rlMsgTagField = value;
                    this.RaisePropertyChanged("rlMsgTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlProject {
            get {
                return this.rlProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.rlProjectField, value) != true)) {
                    this.rlProjectField = value;
                    this.RaisePropertyChanged("rlProject");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlService {
            get {
                return this.rlServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.rlServiceField, value) != true)) {
                    this.rlServiceField = value;
                    this.RaisePropertyChanged("rlService");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlSolution {
            get {
                return this.rlSolutionField;
            }
            set {
                if ((object.ReferenceEquals(this.rlSolutionField, value) != true)) {
                    this.rlSolutionField = value;
                    this.RaisePropertyChanged("rlSolution");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rlStep {
            get {
                return this.rlStepField;
            }
            set {
                if ((object.ReferenceEquals(this.rlStepField, value) != true)) {
                    this.rlStepField = value;
                    this.RaisePropertyChanged("rlStep");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GetLog.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLog", ReplyAction="http://tempuri.org/IService1/GetLogResponse")]
        GetLogDLL.GetLog.RecordLog[] GetLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLog", ReplyAction="http://tempuri.org/IService1/GetLogResponse")]
        System.Threading.Tasks.Task<GetLogDLL.GetLog.RecordLog[]> GetLogAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GetLogDLL.GetLog.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GetLogDLL.GetLog.IService1>, GetLogDLL.GetLog.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GetLogDLL.GetLog.RecordLog[] GetLog() {
            return base.Channel.GetLog();
        }
        
        public System.Threading.Tasks.Task<GetLogDLL.GetLog.RecordLog[]> GetLogAsync() {
            return base.Channel.GetLogAsync();
        }
    }
}
